### PR TITLE
Update Screen_OffsetY.txt

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by HoraceAndTheSpider** [comment]
Eventually, when Amiberry goes SDL2 only, there should be an auto-size function which will cover 90% of cases. For now, I'm happy to go with user recommendations. 

A few i had noticed were a little bit larger than requirements, but this may have been changed as a result of Amiberry updates.

**Comment by ghost** [comment]
Yes I noticed this too, someone has made some 20 when Amiberry only goes to 16 ! (If this  what you are talking about).

**Comment by HoraceAndTheSpider** [comment]
well more the fact that Bloodwych was set to 14 i think and needed to be about 11 ... and IK+ was 11 and only needed 9 IIRC.

**Comment by ghost** [comment]
IK+ doesn't need any Offset if the Screen Height is 216.

**Pull request merged**
