### PR TITLE
Update WHD_Longname_Fixes.txt

### PR DESCRIPTION
**Pull request by ghost**
Last pull request for this year. I only did a rough scan on a very custom English only set. I never bothered with the word `the` at the beginning/end of the names as it's pointless. I also never checked any CD32/CDTV versions. A lot of the names look a lot more correct now though.

### CODE REVIEW

**Comment by HoraceAndTheSpider** [comment]
Actually anything with a “the” should be moved to the end.

Eg New Zealand Story, The 

This can help with accuracy on game scraping for example. E.g “The Power” If shortened to “Power” could return a falseo positive with some scrapers on “Power Drift” for example. 

I will be looking at how I can fix some/most of that in automation at some point :)

**Comment by ghost** [comment]
I didn't think scrapers were that dumb ! Maybe if two games have the same name e.g.

Manager
Manager, The

There aren't that many games with `The` in the title anyway that would make a difference. Muldjord's scraper didn't give many successful results even with completely different names. It was downloading different box art to the in-game image etc.

**Comment by ghost** [comment]
When you're ready ! So I can re-scan my collection. I'm using my own matched screenshots anyway as scraping without CRC etc. is pot luck. Just to clarify, there were NO games in this list previously that had 'the' at the beginning or end of any game so scraping will be no worse (probably better) than previous scrapes.

**Comment by ghost** [comment]
bump :+1:

**Pull request merged**
